export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_DETAILS = "USER_DETAILS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";